### PR TITLE
feat: brought back secret indexing popup in overview page

### PR DESCRIPTION
**Pull request by akhilmhdh**
# Description 📣

1. Brought back secret blind indexing popup in secret overview page for user attention

## Type ✨

- chore

# Tests 🛠️

```sh
# Here's some code block to paste some code snippets
```

---

- [ ] I have read the [contributing guide](https://infisical.com/docs/contributing/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/code-of-conduct). 📝

### CODE REVIEW

**Comment by maidul98** [comment]
Wow, why so many additions

**Comment by maidul98** [comment]
The reason it was commented out was because members would the pop up, but only admins can take action on it. Also because members can't fetch the status, it defaults the showing the section anyways. What we can do is make it so that this pop is only shown to admins or shown to both admins + members but disable the buttom for members. Let me know what you think

**Comment by akhilmhdh** [comment]
Roger that. Will make that change and the other addition is the fix for recursion bug caused by radix ui dependency collision

**Comment by akhilmhdh** [comment]
@maidul98 only admins will get the popup now

**Review by maidul98 — APPROVED** [review]
tested on my end too, works as expected

**Pull request merged**
