### PR TITLE
Make secret type field configurable

### PR DESCRIPTION
**Pull request by Allex1**
# Description 📣

Hi, I know this is not yet complete as it needs docs, examples updated but wanted to get an opinion on this intial draft.
Addresses https://github.com/Infisical/infisical/issues/859

## Type ✨

- [x] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation

# Tests 🛠️

Rebuilt docker image ,started it in k8s and used it with a resource :

```sh
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: docker-release
spec:
  hostAPI: https://infisical.xxx.com/api
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-servicetoken
        secretNamespace: infisical-operator
      secretsScope:
        envSlug: common
        secretsPath: /imagePullSecret
  managedSecretReference:
    secretName: docker-release
    secretNamespace: infisical-test
    secretType: "kubernetes.io/dockerconfigjson"
```

---

- [x] I have read the [contributing guide](https://infisical.com/docs/contributing/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/code-of-conduct). 📝

### CODE REVIEW

**Comment by maidul98** [comment]
Thank you for the PR @Allex1. We will aim to get this reviewed before end of this week

**Comment by maidul98** [comment]
Hey @Allex1 I reviewed the PR and saw that you added a secret type field. I don't think this will suffice as each secret type has it's own format and fields that need to be filled out accordingly. 

What we need is some Go Lang secret templating system that can format the secret from Infisical into the desired Kubernetes secret type. External secrets manager does like this: https://external-secrets.io/v0.4.3/guides-common-k8s-secret-types/. I will dive into this to see what we can do from our end

**Comment by Allex1** [comment]
@maidul98 I may have been a bit too optimistic in my description 😊
Like you said this pr only allows to define the secret type but in our case that is enough to be able to use the infisical operator to generate a secret of type .dockerconfigjson which we need to pull images from our private repo. 

If I change the description and crd to only make the type configurable instead of the current hardcoded `Opaque` will you be willing to allow this functionality merged/released until you will address all of the secret types/formats ? 
In the current setup we really need this and would rather not fork/maintain our own version until you make it available .
Also `managedSecretReference` seemed like the obvious place to define the type but let me know if you have other recommendations.
Thanks .

**Comment by maidul98** [comment]
The Kube secret type of `kubernetes.io/dockercfg` has a different structure than `Opaque`. Are you planning on simply adding a key called `.dockercfg` in Infisical for time being? Is it that you tried to already set your auth details to that key but now only missing the type of the secret created?

**Comment by Allex1** [comment]
I'm actually talking about `kubernetes.io/dockerconfigjson`  which has the same secret structure as `Opaque`  as long as the  encoded string is defined as `.dockerconfigjson` and the type is `kubernetes.io/dockerconfigjson`. So all is needed it the `type` field to be configurable and [not hardcoded](https://github.com/Infisical/infisical/pull/1182/files#diff-e032d6c97bdcf5bd7f3b390f751eb1b7ab38ac3402513e35336e69fbcb85c2a1L145) to `Opaque`
Built the operator from this pr, tested and it's working fine. 
I'll update the pr with the correct description and field options.

**Comment by Allex1** [comment]
@maidul98 updated the pr to only allow for the `type` field to be configurable which should be a good step forward in supporting other secret types and also allow users to use `.dockerconfigjson` . Also kept this change backwards compatible by having the field optional and defaulting to `Opaque` if not provided, basically keeping the existing behavior. 
Let me know if there is something else that needs addressing .
Thanks

**Review by maidul98 — APPROVED** [review]

**Pull request merged**
