### PR TITLE
Update dashboard component

### PR DESCRIPTION
**Pull request by SH5H**
issue: #47 

I convert components in the dashboard to typescript.

and I check the drag & drop feature 

https://user-images.githubusercontent.com/25437192/205468840-c0590f91-0a4e-4906-8ac1-433ffbaa59c8.mov

### CODE REVIEW

**Comment by mv-turtle** [comment]
@SH5H Quick question. Do UIEvent and WheelEvent need to be imported? It seems like they are not used anywhere if I understand correctly. Otherwise looks very good! Thank you so much :)

Screenshot 2022-12-03 at 23 29 01

**Comment by SH5H** [comment]
Oh, that's my mistake.
Maybe we have to add a lint rule to avoid this happening.
May I add some lint rules??

**Comment by SH5H** [comment]
I remove useless types.
And at last time, I forget to submit the Dropzone component So I add it this time

**Review by mv-turtle — APPROVED** [review]
This makes sense! Thank you so much for contributing :)

**Comment by mv-turtle** [comment]
@SH5H Definitely! Feel free to add some lint rules, I think we can make our lint a bit stricter. Thank you!

**Pull request merged**
