### PR TITLE
Adding automatic linter for checking commit

### PR DESCRIPTION
**Pull request by SH5H**
delete the prettier option in the automatic linter
and add `--ignore-scripts` for every `npm install` command

### CODE REVIEW

**Comment by mv-turtle** [comment]
Hi @SH5H! Why do you want to delete prettier? :)

**Comment by maidul98** [comment]
> Why do you want to delete prettier? :)

Because its style is too restrictive and causes unnecessary changes during commit. I will review this @SH5H. I'll update you once I finish!

**Comment by maidul98** [comment]
Small nit, can you pease delete any pretier related files such as `.prettierrc` and resubmit PR? Otherwise, looks good!

**Comment by SH5H** [comment]
I can't update the frontend package file.
Even I update the lock file, the CI Process is always failed.
Can you delete the `prettier` in package dev dependency and update the frontend lock file instead of me?

**Review by maidul98 — APPROVED** [review]
You have to run `npm install` so that the lock file auto updates but sounds good, i'll do it! Thank you so much

**Comment by SH5H** [comment]
> You have to run `npm install` so that the lock file auto updates but sounds good, i'll do it! Thank you so much

I did, but it didn't work

**Pull request merged**
