### PR TITLE
Replace Sentry error handling logic

### PR DESCRIPTION
**Pull request by Spelchure**
# Description 📣

I would like to replace Sentry logs. Am i doing correctly ?. If i am doing correctly i will continue it. Is it 
**breaking change ?** Sorry i am new. I appreciate for any responses.
## Type ✨

- [ ] Bug fix
- [ ] New feature
- [x] Breaking change
- [ ] Documentation

# Tests 🛠️

*Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. You may want to add screenshots when relevant and possible*

```sh
# Here's some code block to paste some code snippets
```

---

- [x] I have read the [contributing guide](https://infisical.com/docs/contributing/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/code-of-conduct). 📝

### CODE REVIEW

**Comment by dangtony98** [comment]
Hi @Spelchure!

This is on the right track — That's correct, you just have to replace the Sentry errors with the appropriate errors in `utils/errors.ts`.

The part that's missing is that we need to remove all the `try-catch` blocks so that the errors get propagated to the error-handling middleware [here](https://github.com/Infisical/infisical/blob/main/backend/src/middleware/requestErrorHandler.ts). 

Can you help remove the `try-catch` blocks?

**Comment by Spelchure** [comment]
Got it. I will work on it thanks.

**Comment by dangtony98** [comment]
Yeah now that I think of it, basically we want:

1. Remove `try-catch` blocks from the backend to propagate to the error-handing middleware at the end.
2. Replace instances of throwing generic errors like `throw new Error()` with one of the errors in `utils.errors.ts`.

**Comment by Spelchure** [comment]
Okay i gonna work it

**Comment by maidul98** [comment]
Hey @Spelchure just checking in, did you need a hand on this? Let us know

**Comment by Spelchure** [comment]
Oh sorry i could not take care of for some reasons, i will work on it this weekend

**Comment by PylotLight** [comment]
@Spelchure How'd you go? happy to continue this one if you wanted to commit what you got so far. I'm fairly desperate for better logging :P

**Comment by Spelchure** [comment]
Yeah i changed some files but there are so many files. I think we should split process for preventing any merge conflicts. I am planning to push my changes after successful rebase

**Comment by Spelchure** [comment]
Hi @PylotLight  i pushed my changes.

**Comment by dangtony98** [comment]
Hi @Spelchure could you resolve the merge conflicts first? Happy to review after.

Awesome job super excited for this one 😄

**Comment by Spelchure** [comment]
Oh @dangtony98  i forgot rebasing i am fixin now

**Comment by Spelchure** [comment]
@dangtony98 just solved conflicts.

**Comment by dangtony98** [comment]
Hi @Spelchure!

Just enabled the workflows to run and it looks the build is failing on some type errors. Can you check those out?

**Comment by Spelchure** [comment]
@dangtony98  completed type errors  :+1:

**Comment by dangtony98** [comment]
Cool almost there. @Spelchure it looks like a few tests are failing now.

If you `cd backend` and run `npm run test` then it'll run some basic tests for secrets/crypto functions; since the custom `throw Error` messages have been removed, they should now expect different error messages.

Can you modify those so that the tests pass? It should be super easy.

**Comment by dangtony98** [comment]
@Spelchure Oh also this PR doesn't replace all the Sentry error handling logic right (just mainly in `helpers` and `integrations`)?

There're still a lot of them in the `controller` files.

**Comment by dangtony98** [comment]
@Spelchure Sounds good to me!

Let me know when you get the tests to pass.

**Comment by Spelchure** [comment]
@dangtony98  tests are passing now

**Comment by dangtony98** [comment]
Awesome. Merged!

Let's continue removing the Sentry and try-catch blocks. We're super close here haha

**Comment by Spelchure** [comment]
@dangtony98 Did you completed replacement otherwise i can go on

**Comment by dangtony98** [comment]
@Spelchure Yeah I merged the changes to `main` a few days ago!

Feel free to continue to go on and do the rest 😄

**Comment by dangtony98** [comment]
Hi @Spelchure!

Just checking in to see if this is still being worked on!

**Comment by Spelchure** [comment]
@dangtony98 Yeah i am progressing

**Comment by Spelchure** [comment]
Hi @dangtony98  i opened pr about sentry logs can you look on it ?

**Pull request merged**
