### PR TITLE
FEAT: replace digit code with email signup link

### PR DESCRIPTION
**Pull request by khoa165**
# Description 📣
FEAT: replace digit code with email signup link
[Issue 58](https://github.com/Infisical/infisical/issues/58)

## Type ✨

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation

# Tests 🛠️
https://www.loom.com/share/3ed03c737c5f4757bd29565867a54670?sid=0e46e618-55b3-4519-9bd0-234a5060a4aa
---

- [x] I have read the [contributing guide](https://infisical.com/docs/contributing/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/code-of-conduct). 📝

### CODE REVIEW

**Comment by dangtony98** [comment]
Looks good to me from the backend; the functionality worked well!

I glossed over the frontend but @vmatsiiako can you give it a look? — Prolly more familiar with the signup sequence.

**Comment by khoa165** [comment]
Hope the Loom video is useful to peek at frontend. Lemme know if you want me to make any changes @vmatsiiako

**Comment by maidul98** [comment]
Can you please verify that when SMTP related environments are not added to the backend, the step to confirm the users email is skipped?

**Comment by vmatsiiako** [comment]
This looks great to me! The only small thing is: in the email, should we give people both the button and the link? This way people can copy it easier

**Comment by dangtony98** [comment]
I think the button should be good (people can right-click it to get the link); I don't think having the link explicitly there is common-practice.

I'll do one last run through it and check for the edge-case @maidul98 highlighted today, then merge :)

**Comment by khoa165** [comment]
@dangtony98 Hi Tony, indeed I didn't skip step 2 when smtp is not configured. My latest commit should have that fix. Before, step 2 always made the request to backend regardless if there is smtp or not, and even without the code, the server still returns 200 (which does not make sense) hence step 2 is skipped to step 3 regardless. Anyway, I fixed that, hope all should be good to merge. My latest commit changed like 1 or 2 lines so should be easy to review

**Comment by dangtony98** [comment]
@maidul98 Can you take a look at this?

I've tried the flow without SMTP configured and it didn't work; it skipped the user email confirmation step but when completing the user's account, it errored out on this in `v3/signupController.ts`:

```js
if (!user || (user && user?.publicKey)) {
	return res.status(403).send({
		error: "Failed to complete account for complete user",
	});
}
```

Is the flow typically supposed to work when SMTP is not configured?

**Comment by maidul98** [comment]
The issue is you never called `checkEmailVerificationCode`.  `checkEmailVerificationCode` needs to be called with a code even when smtp is disabled. This is because when this api call is made, it will create the user with a email which is needed for next step. 

Because SMTP is disabled, the server will not do a code verification match as shown here https://github.com/Infisical/infisical/blob/6d807c0c742e724362fd06e49cee502b683045cd/backend/src/controllers/v1/signupController.ts#L75

**Comment by maidul98** [comment]
Closing due to inactivity

**Comment by vikramnagwal** [comment]
@maidul98 , is this issue still open? I think adding a verify account button will resolve this issue, as well as #1582.

**Pull request closed without merging**
