### PR TITLE
Feat/slack integration

### PR DESCRIPTION
**Pull request by quinton11**
# Description 📣

Slack integration into CLI release workflow so users can subscribe to be notified of updates

Issue: See #198 

Motivation: This is to allow slack users subscribe to be alerted on latest releases relating to the infisical cli.

Dependencies:
- Requires a SLACK_WEBHOOK and SLACK__ICON github secret.

### CODE REVIEW

**Comment by maidul98** [comment]
With this approach, users will only know of new CLI updates if they are in our slack. I think it'd be more useful if this was a slack bot that people can install in their workspaces. Let me know what you think

**Comment by quinton11** [comment]
Updated PR. To use you would have to provide a SLACK_BOT_TOKEN env variable after creating your slack app. As well as the message you intend to broadcast. Currently its just a basic text.

How it works?
It uses a custom github action (see https://github.com/Infisical/infisical/pull/498/files#diff-33ba490cb8145b58db19f4dd0f72ccfddae4b86d5fde272a1d3c6c9ce964514a) to get all channels, both private and public associated with your bot token (When users install your bot and invite them into channels) and broadcasts the message you provide to each channel.

**Comment by maidul98** [comment]
Closing for now as it is not a top priority

**Comment by Salmaan-M** [comment]
Can we open this issue again ?, i would love to work on it.

**Pull request closed without merging**
