### PR TITLE
Add husky and lint-staged

### PR DESCRIPTION
**Pull request by SH5H**
issue: #85 

Now, can lint for staged files automatically.

You can install 'husky' and 'lint-staged' manually at the root with `npm install` command.

But if you execute `npm install` in the backend or frontend folder,  all of these processes will be executed automatically.

and I moved files for prettier to the root location.

### CODE REVIEW

**Comment by SH5H** [comment]
I don't know why CI for the frontend is failing...
Even though I've updated package-lock.json, CI is still falling.


Before merging this PR, please modify the package.json in the root.

**Comment by maidul98** [comment]
Did you do `npm install` for the frontend before you submitted the PR? if not maybe try to do it again with new commit

**Comment by SH5H** [comment]
[40b42fd](https://github.com/Infisical/infisical/pull/111/commits/40b42fdcb5b21f3f2d39034edebd18238bc59cb5) I've updated the lock file in this commit. But it couldn't fix the CI error.
So, I brought the last version...

**Comment by maidul98** [comment]
Just tested it and it works great. The prettier format is definitely a bit aggressive but that might be okay. Great work 💥💥

**Review by maidul98 — APPROVED** [review]
Looks good to me! Mergeing

**Pull request merged**
