### PR TITLE
Add helper text and tooltip for secret path

### PR DESCRIPTION
**Pull request by JanetEne**
# Description 📣

This PR updates the placeholder for the secret path to be less confusing and includes a helper text telling users that they can use glob patterns. It also adds a tooltip containing examples of various glob patterns they can use.

Fixes Issue: [#946](https://github.com/Infisical/infisical/issues/946)

## Type ✨

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation

# Tests 🛠️

This screenshot shows the design for the secret path field, The input field shows the updated placeholder wth the helper texts and also an info icon which the user clicks to  show examples of glob patterns

image

image

## [Preview Demo](https://www.loom.com/share/3599af38affa4532b744e81491d56222?sid=fd3c2950-5af6-461c-aeeb-4ed9b159898a)

- [x] I have read the [contributing guide](https://infisical.com/docs/contributing/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/code-of-conduct). 📝

### CODE REVIEW

**Comment by vmatsiiako** [comment]
Hi @JanetEne! I just had a look at the PR. I think the note should show on on hover rather than on click. Do you think you would be able to tweak this?

**Comment by JanetEne** [comment]
Sure i can, will update ASAP!

**Comment by JanetEne** [comment]
@vmatsiiako it has been updated

**Review by vmatsiiako — APPROVED** [review]
@JanetEne this looks great! Merging.

Thank you so much for your contribution :)

**Pull request merged**
