### PR TITLE
added prettier-plugin-tailwindcss

### LINKED ISSUE #252: Add "prettier-plugin-tailwindcss"
### Automatic Class Sorting with Prettier 
It will sort the tailwind class names when we save the file.

## Why it is Useful?
- It brings consistency to the code.
- It is recommended by the creators of Tailwind.
- This plugin will improve the developer experience.

## ADITIONAL CONTEXT
https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

**Can I raise a PR?**

### PR DESCRIPTION
**Pull request by sanyamjain04**
Fixed #252 Added Prettier-plugin-tailwindcss.

### CODE REVIEW

**Review by asheliahut — CHANGES_REQUESTED** [review]
Can you make sure to run `npm install` so that the package.lock.json also gets updated accordingly.

**Comment by sanyamjain04** [comment]
> Can you make sure to run `npm install` so that the package.lock.json also gets updated accordingly.

Done.

**Comment by sanyamjain04** [comment]
I don't know why merge conflict is occurring.
It may be because I updated my branch with the main one.
I am closing this PR and Creating a new one.

**Comment by sanyamjain04** [comment]
Sorry for merge conflict.
I have created a new PR with no conflicts #265

**Pull request closed without merging**
