### PR TITLE
issue-833 - Using EMAIL for authentication, the EMAIL address is case…

### PR DESCRIPTION
**Pull request by subhajit20**
… sensitive fixed

# Description 📣

Fixed following bug - Using EMAIL for authentication, the EMAIL address is case #833

## Type ✨

- [X] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation
---

- [X ] I have read the [contributing guide](https://infisical.com/docs/contributing/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/code-of-conduct). 📝

### CODE REVIEW

**Comment by maidul98** [comment]
@subhajit20 i just tested out the PR and I wasn't able to get it to work. Can you test it on your end in local devlopment and see if it works for you?

**Comment by subhajit20** [comment]
> @subhajit20 i just tested out the PR and I wasn't able to get it to work. Can you test it on your end in local devlopment and see if it works for you?

Have One question,  will I have to do changes in two login routes api at the same time ?

**Comment by dangtony98** [comment]
@subhajit20 You mean `login1` and `login2`? — The changes should be made to `login1` and `login2` in the `v3` endpoints; this is the correct location.

**Comment by subhajit20** [comment]
> @subhajit20 You mean `login1` and `login2`? — The changes should be made to `login1` and `login2` in the `v3` endpoints; this is the correct location.

Okay.

**Comment by subhajit20** [comment]
> @subhajit20 You mean `login1` and `login2`? — The changes should be made to `login1` and `login2` in the `v3` endpoints; this is the correct location.

Hey, I have tested locally and seen that it only takes the test@localhost.local email for login, any other different email is not working.

**Comment by maidul98** [comment]
This PR is now stale, the backend has moved to Postgres. Closing for now

**Pull request closed without merging**
