### PR TITLE
feat(core): Group support for access requests

### PR DESCRIPTION
**Pull request by DanielHougaard**
# Description 📣

This PR introduces group support for access requests. Groups have a separate database column for memberships, making it impossible to directly reference it without having to make a new field specifically for the group membership. We've moved away from using the project membership ID, to instead use a user ID / project ID combination, as this will give the same result but with more flexibility.

## Type ✨

- [x] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation

---

- [x] I have read the [contributing guide](https://infisical.com/docs/contributing/getting-started/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/getting-started/code-of-conduct). 📝

### CODE REVIEW

**Review by akhilmhdh — COMMENTED** [review]
@DanielHougaard I don't see the logic to delete project user additional privileges as now they are user ids. On the even of leaving/removing from a project as there membership is not linked they won't get removed right?

**Comment by DanielHougaard** [comment]
> @DanielHougaard I don't see the logic to delete project user additional privileges as now they are user ids. On the event of leaving/removing from a project as there membership is not linked they won't get removed right?

@akhilmhdh, you're right! Privileges should be cleaned up once the user loses access to the project or organization, and I've updated the PR to handle this. I've decided to not clean up access requests as I think it makes sense that the user is able to keep a record of all access requests that were made in the past, regardless of if the user has been removed from the project or not. 

https://github.com/Infisical/infisical/pull/2172/commits/b702ffb668eeeca2a8dedfc4df815ddbfb1a0139

**Review by akhilmhdh — APPROVED** [review]
Code wise looking good to me. Need to test it.

**Comment by maidul98** [comment]
@DanielHougaard have you tested this thoroughly?

**Comment by DanielHougaard** [comment]
> @DanielHougaard have you tested this thoroughly?

Yes, but I would like to test this additionally on Gamma prior to full release

**Pull request merged**
