### PR TITLE
fix: secret input editor bugs

### PR DESCRIPTION
**Pull request by G3root**
# Description 📣

this PR replace the content-editable based editor with HTML textarea element. which is more accessible and less buggy

### one of the bugs in the current editor.

[Screencast 2023-09-18 21:56:09.webm](https://github.com/Infisical/infisical/assets/84864519/19881c38-4e78-48ef-a1e9-f1e74c34fd45)

### after:

[Screencast 2023-09-18 21:58:25.webm](https://github.com/Infisical/infisical/assets/84864519/d4aa66dd-1493-44aa-8106-f6c4a1c8ab92)

## Type ✨

- [x] Bug fix

- [x] I have read the [contributing guide](https://infisical.com/docs/contributing/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/code-of-conduct). 📝

### CODE REVIEW

**Comment by akhilmhdh** [comment]
Hey there @G3root 

I just tried out your PR and there are some issues with it though.

1. We used content editable because we wanted multi line input. When you type enter it should go to next line
2. I see for some reason space is also not working in here. 
3. So we switched to content editable to ensure a multiline input with syntax highlighting and scrollable. With these textarea was never working. 


I see that's a bug indeed. will need to test that out. I am hesistant to introduce a library that uses a small editor. But as we are spending quite time on this single component ill probably use what Linear is using. @maidul98

**Comment by G3root** [comment]
@akhilmhdh  pushed a fixed for multi line input but as you previously pointed out that making the content scrollable was a challenging task.

**Comment by G3root** [comment]
update: made the editor scrollable

[Screencast 2023-09-19 00:24:51.webm](https://github.com/Infisical/infisical/assets/84864519/61b05b78-e331-47e7-a529-6c8e4257c874)

**Review by akhilmhdh — CHANGES_REQUESTED** [review]
Tested  the component and wow nice work.

Although one small change a weird padding at bottom:

Screenshot 2023-09-19 at 10 52 31 AM

Screenshot 2023-09-19 at 10 58 37 AM

**Comment by G3root** [comment]
@akhilmhdh The padding was intentionally added to avoid caret misalignment when line breaks occur. It's a workaround for now, Any suggestions would be appreciated.

**Comment by akhilmhdh** [comment]
Ohh then ill look at later. The padding makes it look weird.

**Comment by akhilmhdh** [comment]
hey @G3root . Closing this PR as i pulled your changes and fixed the issues had to raise another PR from my side #1010 

As i created another branch to review. No worries  your commits are  right their.

**Comment by G3root** [comment]
> hey @G3root . Closing this PR as i pulled your changes and fixed the issues had to raise another PR from my side #1010 
> 
> As i created another branch to review. No worries  your commits are  right their. 

@akhilmhdh All good  👍

**Pull request closed without merging**
