### PR TITLE
feat: cli export allow filtering with tags

### LINKED ISSUE #705: [ENG-145] tags filter not working while exporting via cli
Trying to export secrets based on tags does not work via the cli tool

### To Reproduce

Set some tags on secrets and pass the --tags option to the cli as descibed in the --help documentation

` -t, --tags string         filter secrets by tag slugs`

### Expected behavior

To filter by tags

### Platform you are having the issue on:

Linux amd64

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-145](https://linear.app/infisical/issue/ENG-145/tags-filter-not-working-while-exporting-via-cli)</sub>

### PR DESCRIPTION
**Pull request by quinton11**
## Description 📣
Closes #705

### CODE REVIEW

**Comment by Salman2301** [comment]
I saw that you are removing the secrets based on the for loop. Nice patch but
Would be better if we pass the secrets filtering to the api

After some drill down of this code... Found this commented piece
https://github.com/Infisical/infisical/blob/8893aec213b58dca4595300c51bbf546c25c67a9/cli/packages/util/secrets.go#L164

Basically need to implement filter by tag in the API (v3)
https://github.com/Infisical/infisical/blob/8893aec213b58dca4595300c51bbf546c25c67a9/backend/src/helpers/secrets.ts#L516-L524

**Comment by quinton11** [comment]
@Salman2301  based on the nature of the project I believe decryption of secrets is handled on the client side via the private key, by extension that means filtering via key words would happen there as well(same happens on the frontend).  Filtering at the api side will mean the backend having access to the user's private key. That is of course if you have a way of filtering encrypted secrets. I may be wrong and I stand corrected

**Comment by Salman2301** [comment]
Sorry for the confusion, I mean filter using the tags.... Infisical doesn't store the raw secret value... but the tags associated with secret which is what the pull request solving are stored as string[] ( foreign key to the tag database). We can just query tags using the Orm if the user provided. I believe I could be wrong here too.

**Comment by quinton11** [comment]
@Salman2301 Right, must've misunderstood, that would work I believe, will take a look

**Comment by maidul98** [comment]
For now client side filetering works fine. @Salman2301 filtering at API level can be added in the future

**Review by maidul98 — APPROVED** [review]

**Pull request merged**
