### PR TITLE
Stop ability to rename a secret to empty name from frontend

### PR DESCRIPTION
**Pull request by rhythmbhiwani**
# Description 📣

Fixes a bug from frontend side, which previously allowed secrets to be renamed to empty string, thus breaking the system as they won't be able to rename or delete that secret again. Added a check to update the key only if it has value.

- TODO
Although this change is done from frontend, but this validation should also be in backend, which restricts the secret name to be sent as empty

## Type ✨

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation

# Tests 🛠️
Attached video for reference

https://github.com/Infisical/infisical/assets/47269183/d9c7dbd6-7daa-4826-833d-af3020aa6253

---

- [x] I have read the [contributing guide](https://infisical.com/docs/contributing/getting-started/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/getting-started/code-of-conduct). 📝

### CODE REVIEW

**Comment by rhythmbhiwani** [comment]
Which one of these looks good to inform the user
CC: @Grraahaam 
Screenshot 2024-03-02 at 6 33 44 PM
Screenshot 2024-03-02 at 6 34 08 PM
Screenshot 2024-03-02 at 6 34 19 PM

**Comment by rhythmbhiwani** [comment]
Screenshot 2024-03-02 at 7 44 12 PM
Updated to look like this when trying to submit

**Review by DanielHougaard — CHANGES_REQUESTED** [review]
Really great find, this is great!

One small change I'd like to request though, is instead of allowing the user to click the save button, and displaying an error, we should do something a little different. 

Instead, I think we should fully just disable the save secret button when the key is empty. Additionally I think we should also add a check for this on the backend. We could use our zod schema validation to check this.

**Comment by rhythmbhiwani** [comment]
https://github.com/Infisical/infisical/assets/47269183/e8b59bcc-3f2e-468b-818e-e3ddfa936ecc

Updated the frontend to disable save button if secret name is empty

**Review by DanielHougaard — APPROVED** [review]
I committed my backend change to also make it impossible to do this through the API. Really awesome work, approved!

**Pull request merged**
